default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nelsonsupholstery_development

test:
  <<: *default
  database: nelsonsupholstery_test

production:
  <<: *default
  database: nelsonsupholstery_production
  username: nelsonsupholstery
  password: <%= ENV['NELSONSUPHOLSTERY_DATABASE_PASSWORD'] %>
